name : Mock Deploy Pipeline (Test)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
    mock-build:
      runs-on: ubuntu-latest
      outputs:
        image: ${{steps.build.outputs.image}}
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Mock - Configure AWS credentials
          run: echo "aws-configuration Test"/.